"""Current Kerala PSC posts that should sit first in SEO, exam lists, and practice banks."""
from typing import Optional

PRIORITY_EXAMS = [
    {
        "rank": 1,
        "slug": "village-field-assistant",
        "name": "Village Field Assistant",
        "cat_no": "571/2025",
        "level": "SSLC",
        "duration_minutes": 90,
        "opportunity": "Exam 17 Oct and 31 Oct 2026",
        "question_keywords": ["agriculture", "crop", "soil", "irrigation", "fertilizer", "paddy", "farmer", "village"],
        "syllabus": [
            {"topic": "History", "marks": 5},
            {"topic": "Geography", "marks": 5},
            {"topic": "Economics", "marks": 5},
            {"topic": "Constitution and Polity", "marks": 5},
            {"topic": "Facts About Kerala", "marks": 5},
            {"topic": "Biology and Public Health", "marks": 6},
            {"topic": "Physics", "marks": 3},
            {"topic": "Chemistry", "marks": 3},
            {"topic": "Arts Culture Literature Sports", "marks": 5},
            {"topic": "Computer", "marks": 3},
            {"topic": "Important Laws", "marks": 5},
            {"topic": "Vocational Agriculture Topics", "marks": 20},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
        ],
        "topic_fallbacks": {
            "Vocational Agriculture Topics": ["Biology", "Science", "Facts About Kerala"],
        },
    },
    {
        "rank": 2,
        "slug": "junior-lab-assistant",
        "name": "Junior Lab Assistant",
        "cat_no": "733/2025",
        "level": "Plus Two Science",
        "duration_minutes": 90,
        "opportunity": "OMR exam 3 October 2026",
        "apply_by": None,
        "question_keywords": ["microscope", "centrifuge", "titration", "pipette", "reagent", "bacteria", "cell", "acid", "alkali", "laboratory", "mitosis", "enzyme"],
        "syllabus": [
            {"topic": "Lab Safety and Instruments", "marks": 20},
            {"topic": "Physics", "marks": 20},
            {"topic": "Chemistry", "marks": 20},
            {"topic": "Biology and Public Health", "marks": 20},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Maths", "marks": 10},
        ],
        "topic_fallbacks": {
            "Lab Safety and Instruments": ["Science", "Chemistry", "Physics", "Biology"],
            "Physics": ["Science"],
            "Chemistry": ["Science"],
            "Biology and Public Health": ["Biology", "Science", "Public Health"],
        },
    },
    {
        "rank": 3,
        "slug": "motor-mechanic",
        "name": "Motor Mechanic",
        "cat_no": "630/2025",
        "level": "ITI",
        "duration_minutes": 90,
        "opportunity": "Online exam 13 October 2026",
        "question_keywords": ["engine", "piston", "clutch", "brake", "gear", "carburettor", "carburetor", "diesel", "petrol", "steering", "lubricant", "spark", "crankshaft", "injector", "alternator"],
        "syllabus": [
            {"topic": "Engine and Fuel System", "marks": 20},
            {"topic": "Brake Clutch and Transmission", "marks": 20},
            {"topic": "Steering and Suspension", "marks": 10},
            {"topic": "Cooling and Lubrication", "marks": 10},
            {"topic": "Auto Electrical", "marks": 15},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 5},
        ],
        "topic_fallbacks": {
            "Engine and Fuel System": ["Science", "Physics"],
            "Brake Clutch and Transmission": ["Science", "Physics"],
            "Steering and Suspension": ["Science", "Physics"],
            "Cooling and Lubrication": ["Science", "Physics"],
            "Auto Electrical": ["Science", "Physics"],
        },
    },
    {
        "rank": 4,
        "slug": "special-branch-assistant",
        "name": "Special Branch Assistant",
        "cat_no": "Various / 2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "Shortlist published Sept 2026",
        "syllabus": [
            {"topic": "History", "marks": 8},
            {"topic": "Geography", "marks": 7},
            {"topic": "Constitution and Polity", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 8},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
            {"topic": "Science", "marks": 7},
            {"topic": "Special Branch and Police Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Special Branch and Police Topics": ["Constitution", "Important Laws", "History"],
        },
    },
    {
        "rank": 5,
        "slug": "civil-excise-officer",
        "name": "Civil Excise Officer",
        "cat_no": "Various / 2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "Current PSC examination updates",
        "syllabus": [
            {"topic": "History", "marks": 8},
            {"topic": "Geography", "marks": 7},
            {"topic": "Constitution and Polity", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 8},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
            {"topic": "Science", "marks": 7},
            {"topic": "Excise Special Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Excise Special Topics": ["Important Laws", "Constitution", "Economics"],
        },
    },
    {
        "rank": 6,
        "slug": "lineman",
        "name": "Lineman",
        "cat_no": "Various / 2026",
        "level": "ITI",
        "duration_minutes": 90,
        "opportunity": "Shortlists appearing in Sept 2026",
        "question_keywords": ["ohm", "volt", "ampere", "transformer", "motor", "circuit", "fuse", "earthing", "watt", "current", "resistance", "conductor", "electric"],
        "syllabus": [
            {"topic": "Basic Electricity", "marks": 15},
            {"topic": "Ohm's Law and Circuits", "marks": 15},
            {"topic": "Overhead Lines and Safety", "marks": 15},
            {"topic": "Transformers and Distribution", "marks": 15},
            {"topic": "Instruments and Earthing", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
        ],
        "topic_fallbacks": {
            "Basic Electricity": ["Science", "Physics"],
            "Ohm's Law and Circuits": ["Science", "Physics"],
            "Overhead Lines and Safety": ["Science", "Physics"],
            "Transformers and Distribution": ["Science", "Physics"],
            "Instruments and Earthing": ["Science", "Physics"],
        },
    },
    {
        "rank": 7,
        "slug": "nurse-grade-ii",
        "name": "Nurse Grade II",
        "cat_no": "Various / 2026",
        "level": "Nursing",
        "duration_minutes": 75,
        "opportunity": "Active district recruitment/shortlist",
        "question_keywords": ["nurse", "anatomy", "physiology", "first aid", "vaccine", "patient", "hospital", "blood", "infection", "hygiene"],
        "syllabus": [
            {"topic": "Anatomy and Physiology", "marks": 20},
            {"topic": "Fundamentals of Nursing", "marks": 20},
            {"topic": "Community Health and First Aid", "marks": 15},
            {"topic": "Biology and Public Health", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Daily Current Affairs", "marks": 5},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
        ],
        "topic_fallbacks": {
            "Anatomy and Physiology": ["Biology", "Science", "Public Health"],
            "Fundamentals of Nursing": ["Biology", "Public Health", "Science"],
            "Community Health and First Aid": ["Public Health", "Biology", "Science"],
        },
    },
    {
        "rank": 8,
        "slug": "fire-and-rescue",
        "name": "Fire & Rescue Officer",
        "cat_no": "551/2025 + 2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "New 2026 notification categories",
        "question_keywords": ["fire", "rescue", "extinguisher", "combustion", "hose", "ladder"],
        "syllabus": [
            {"topic": "History", "marks": 5},
            {"topic": "Geography", "marks": 5},
            {"topic": "Economics", "marks": 5},
            {"topic": "Constitution and Polity", "marks": 8},
            {"topic": "Facts About Kerala", "marks": 3},
            {"topic": "Biology and Public Health", "marks": 4},
            {"topic": "Physics", "marks": 3},
            {"topic": "Chemistry", "marks": 3},
            {"topic": "Arts Culture Literature Sports", "marks": 4},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
            {"topic": "Fire and Rescue Special Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Fire and Rescue Special Topics": ["Science", "Physics", "Public Health"],
        },
    },
    {
        "rank": 9,
        "slug": "electrician",
        "name": "Electrician",
        "cat_no": "2026 notifications",
        "level": "ITI",
        "duration_minutes": 90,
        "opportunity": "New 2026 notification categories",
        "question_keywords": ["ohm", "volt", "ampere", "transformer", "motor", "circuit", "fuse", "earthing", "watt", "current", "resistance", "alternating", "magnet", "diode", "transistor", "generator", "conductor"],
        "syllabus": [
            {"topic": "Basic Electricity — Fundamentals, Resistance, Conductors, Wires", "marks": 10},
            {"topic": "Ohm's Law — Kirchhoff's Law, Temperature Effects, Cell Types", "marks": 10},
            {"topic": "Magnetism — Properties, Electromagnetism, Fleming's Rules, Faraday's Laws", "marks": 10},
            {"topic": "Alternating Current and Earthing — AC, Earthing, Wiring, Megger", "marks": 10},
            {"topic": "DC Machines — Generators, DC Motors, Starters", "marks": 10},
            {"topic": "AC Motors — Single & 3 Phase, DOL, Star-Delta Starters", "marks": 10},
            {"topic": "Instruments and Transformers — Measuring Instruments, EMF Equation", "marks": 10},
            {"topic": "Illumination and Electronics — Lamps, Semiconductors, Diodes, Transistors", "marks": 10},
            {"topic": "Power Generation — Energy Sources, Types of Power Generation", "marks": 10},
            {"topic": "Transmission and Distribution — AC vs DC Comparison", "marks": 10},
        ],
        "topic_fallbacks": {
            "Basic Electricity — Fundamentals, Resistance, Conductors, Wires": ["Science", "Physics"],
            "Ohm's Law — Kirchhoff's Law, Temperature Effects, Cell Types": ["Science", "Physics"],
            "Magnetism — Properties, Electromagnetism, Fleming's Rules, Faraday's Laws": ["Science", "Physics"],
            "Alternating Current and Earthing — AC, Earthing, Wiring, Megger": ["Science", "Physics"],
            "DC Machines — Generators, DC Motors, Starters": ["Science", "Physics"],
            "AC Motors — Single & 3 Phase, DOL, Star-Delta Starters": ["Science", "Physics"],
            "Instruments and Transformers — Measuring Instruments, EMF Equation": ["Science", "Physics"],
            "Illumination and Electronics — Lamps, Semiconductors, Diodes, Transistors": ["Science", "Physics"],
            "Power Generation — Energy Sources, Types of Power Generation": ["Science", "Physics"],
            "Transmission and Distribution — AC vs DC Comparison": ["Science", "Physics"],
        },
    },
    {
        "rank": 10,
        "slug": "beat-forest-officer",
        "name": "Beat Forest Officer",
        "cat_no": "2026 notifications",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "New 2026 notification categories",
        "question_keywords": ["forest", "wildlife", "sanctuary", "tiger", "elephant", "national park", "biodiversity"],
        "syllabus": [
            {"topic": "History", "marks": 8},
            {"topic": "Geography", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Constitution and Polity", "marks": 8},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Science", "marks": 8},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 8},
            {"topic": "Malayalam", "marks": 8},
            {"topic": "Forest and Wildlife Special Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Forest and Wildlife Special Topics": ["Geography", "Facts About Kerala", "Science"],
        },
    },
    {
        "rank": 11,
        "slug": "laboratory-attender",
        "name": "Laboratory Attender",
        "cat_no": "2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "Application window through 7 Oct 2026",
        "apply_by": "2026-10-07",
        "question_keywords": ["laboratory", "beaker", "burette", "microscope", "acid", "base", "test tube", "pipette", "titration"],
        "syllabus": [
            {"topic": "Physics", "marks": 15},
            {"topic": "Chemistry", "marks": 15},
            {"topic": "Biology and Public Health", "marks": 15},
            {"topic": "Lab Safety and Instruments", "marks": 15},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Daily Current Affairs", "marks": 10},
        ],
        "topic_fallbacks": {
            "Lab Safety and Instruments": ["Science", "Chemistry", "Physics"],
        },
    },
    {
        "rank": 12,
        "slug": "assistant-project-engineer",
        "name": "Assistant Project Engineer",
        "cat_no": "2026",
        "level": "Degree",
        "duration_minutes": 75,
        "opportunity": "Application window through 7 Oct 2026",
        "apply_by": "2026-10-07",
        "syllabus": [
            {"topic": "Engineering Maths", "marks": 20},
            {"topic": "Physics", "marks": 10},
            {"topic": "Basic Engineering and Drawing", "marks": 20},
            {"topic": "Constitution and Polity", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Computer", "marks": 10},
        ],
        "topic_fallbacks": {
            "Engineering Maths": ["Maths"],
            "Basic Engineering and Drawing": ["Science", "Physics", "Maths"],
        },
    },
    {
        "rank": 13,
        "slug": "police-constable-band",
        "name": "Police Constable Band / Bugler / Drummer",
        "cat_no": "2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "Application window through 7 Oct 2026",
        "apply_by": "2026-10-07",
        "question_keywords": ["police", "constable", "ipc", "crpc", "band", "music", "rhythm"],
        "syllabus": [
            {"topic": "History", "marks": 8},
            {"topic": "Geography", "marks": 7},
            {"topic": "Constitution and Polity", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 8},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
            {"topic": "Science", "marks": 7},
            {"topic": "Band Music and Police Special Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Band Music and Police Special Topics": ["Arts Culture Literature Sports", "English", "History"],
        },
    },
]

PRIORITY_SLUGS = [item["slug"] for item in PRIORITY_EXAMS]


from typing import Optional

def priority_rank(slug: Optional[str]) -> int:
    if not slug:
        return 999
    for item in PRIORITY_EXAMS:
        if item["slug"] == slug:
            return item["rank"]
    return 999
