"""Current Kerala PSC posts that should sit first in SEO, exam lists, and practice banks."""
from typing import Optional

PRIORITY_EXAMS = [
    {
        "rank": 1,
        "slug": "special-branch-assistant",
        "name": "Special Branch Assistant",
        "cat_no": "Various / 2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "Shortlist published Sept 2026",
        "syllabus": [
            {"topic": "History", "marks": 8},
            {"topic": "Geography", "marks": 7},
            {"topic": "Constitution and Polity", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 8},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
            {"topic": "Science", "marks": 7},
            {"topic": "Special Branch and Police Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Special Branch and Police Topics": ["Constitution", "Important Laws", "History"],
        },
    },
    {
        "rank": 2,
        "slug": "civil-excise-officer",
        "name": "Civil Excise Officer",
        "cat_no": "Various / 2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "Current PSC examination updates",
        "syllabus": [
            {"topic": "History", "marks": 8},
            {"topic": "Geography", "marks": 7},
            {"topic": "Constitution and Polity", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 8},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
            {"topic": "Science", "marks": 7},
            {"topic": "Excise Special Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Excise Special Topics": ["Important Laws", "Constitution", "Economics"],
        },
    },
    {
        "rank": 3,
        "slug": "lineman",
        "name": "Lineman",
        "cat_no": "Various / 2026",
        "level": "ITI",
        "duration_minutes": 90,
        "opportunity": "Shortlists appearing in Sept 2026",
        "syllabus": [
            {"topic": "Basic Electricity", "marks": 15},
            {"topic": "Ohm's Law and Circuits", "marks": 15},
            {"topic": "Overhead Lines and Safety", "marks": 15},
            {"topic": "Transformers and Distribution", "marks": 15},
            {"topic": "Instruments and Earthing", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
        ],
        "topic_fallbacks": {
            "Basic Electricity": ["Science", "Physics"],
            "Ohm's Law and Circuits": ["Science", "Physics"],
            "Overhead Lines and Safety": ["Science", "Physics"],
            "Transformers and Distribution": ["Science", "Physics"],
            "Instruments and Earthing": ["Science", "Physics"],
        },
    },
    {
        "rank": 4,
        "slug": "nurse-grade-ii",
        "name": "Nurse Grade II",
        "cat_no": "Various / 2026",
        "level": "Nursing",
        "duration_minutes": 75,
        "opportunity": "Active district recruitment/shortlist",
        "syllabus": [
            {"topic": "Anatomy and Physiology", "marks": 20},
            {"topic": "Fundamentals of Nursing", "marks": 20},
            {"topic": "Community Health and First Aid", "marks": 15},
            {"topic": "Biology and Public Health", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Daily Current Affairs", "marks": 5},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
        ],
        "topic_fallbacks": {
            "Anatomy and Physiology": ["Biology", "Science", "Public Health"],
            "Fundamentals of Nursing": ["Biology", "Public Health", "Science"],
            "Community Health and First Aid": ["Public Health", "Biology", "Science"],
        },
    },
    {
        "rank": 5,
        "slug": "fire-and-rescue",
        "name": "Fire & Rescue Officer",
        "cat_no": "551/2025 + 2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "New 2026 notification categories",
        "syllabus": [
            {"topic": "History", "marks": 5},
            {"topic": "Geography", "marks": 5},
            {"topic": "Economics", "marks": 5},
            {"topic": "Constitution and Polity", "marks": 8},
            {"topic": "Facts About Kerala", "marks": 3},
            {"topic": "Biology and Public Health", "marks": 4},
            {"topic": "Physics", "marks": 3},
            {"topic": "Chemistry", "marks": 3},
            {"topic": "Arts Culture Literature Sports", "marks": 4},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
            {"topic": "Fire and Rescue Special Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Fire and Rescue Special Topics": ["Science", "Physics", "Public Health"],
        },
    },
    {
        "rank": 6,
        "slug": "electrician",
        "name": "Electrician",
        "cat_no": "2026 notifications",
        "level": "ITI",
        "duration_minutes": 90,
        "opportunity": "New 2026 notification categories",
        "syllabus": [
            {"topic": "Basic Electricity — Fundamentals, Resistance, Conductors, Wires", "marks": 10},
            {"topic": "Ohm's Law — Kirchhoff's Law, Temperature Effects, Cell Types", "marks": 10},
            {"topic": "Magnetism — Properties, Electromagnetism, Fleming's Rules, Faraday's Laws", "marks": 10},
            {"topic": "Alternating Current and Earthing — AC, Earthing, Wiring, Megger", "marks": 10},
            {"topic": "DC Machines — Generators, DC Motors, Starters", "marks": 10},
            {"topic": "AC Motors — Single & 3 Phase, DOL, Star-Delta Starters", "marks": 10},
            {"topic": "Instruments and Transformers — Measuring Instruments, EMF Equation", "marks": 10},
            {"topic": "Illumination and Electronics — Lamps, Semiconductors, Diodes, Transistors", "marks": 10},
            {"topic": "Power Generation — Energy Sources, Types of Power Generation", "marks": 10},
            {"topic": "Transmission and Distribution — AC vs DC Comparison", "marks": 10},
        ],
        "topic_fallbacks": {
            "Basic Electricity — Fundamentals, Resistance, Conductors, Wires": ["Science", "Physics"],
            "Ohm's Law — Kirchhoff's Law, Temperature Effects, Cell Types": ["Science", "Physics"],
            "Magnetism — Properties, Electromagnetism, Fleming's Rules, Faraday's Laws": ["Science", "Physics"],
            "Alternating Current and Earthing — AC, Earthing, Wiring, Megger": ["Science", "Physics"],
            "DC Machines — Generators, DC Motors, Starters": ["Science", "Physics"],
            "AC Motors — Single & 3 Phase, DOL, Star-Delta Starters": ["Science", "Physics"],
            "Instruments and Transformers — Measuring Instruments, EMF Equation": ["Science", "Physics"],
            "Illumination and Electronics — Lamps, Semiconductors, Diodes, Transistors": ["Science", "Physics"],
            "Power Generation — Energy Sources, Types of Power Generation": ["Science", "Physics"],
            "Transmission and Distribution — AC vs DC Comparison": ["Science", "Physics"],
        },
    },
    {
        "rank": 7,
        "slug": "beat-forest-officer",
        "name": "Beat Forest Officer",
        "cat_no": "2026 notifications",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "New 2026 notification categories",
        "syllabus": [
            {"topic": "History", "marks": 8},
            {"topic": "Geography", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Constitution and Polity", "marks": 8},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Science", "marks": 8},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 8},
            {"topic": "Malayalam", "marks": 8},
            {"topic": "Forest and Wildlife Special Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Forest and Wildlife Special Topics": ["Geography", "Facts About Kerala", "Science"],
        },
    },
    {
        "rank": 8,
        "slug": "laboratory-attender",
        "name": "Laboratory Attender",
        "cat_no": "2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "Application window through 7 Oct 2026",
        "apply_by": "2026-10-07",
        "syllabus": [
            {"topic": "Physics", "marks": 15},
            {"topic": "Chemistry", "marks": 15},
            {"topic": "Biology and Public Health", "marks": 15},
            {"topic": "Lab Safety and Instruments", "marks": 15},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Daily Current Affairs", "marks": 10},
        ],
        "topic_fallbacks": {
            "Lab Safety and Instruments": ["Science", "Chemistry", "Physics"],
        },
    },
    {
        "rank": 9,
        "slug": "assistant-project-engineer",
        "name": "Assistant Project Engineer",
        "cat_no": "2026",
        "level": "Degree",
        "duration_minutes": 75,
        "opportunity": "Application window through 7 Oct 2026",
        "apply_by": "2026-10-07",
        "syllabus": [
            {"topic": "Engineering Maths", "marks": 20},
            {"topic": "Physics", "marks": 10},
            {"topic": "Basic Engineering and Drawing", "marks": 20},
            {"topic": "Constitution and Polity", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 10},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Computer", "marks": 10},
        ],
        "topic_fallbacks": {
            "Engineering Maths": ["Maths"],
            "Basic Engineering and Drawing": ["Science", "Physics", "Maths"],
        },
    },
    {
        "rank": 10,
        "slug": "police-constable-band",
        "name": "Police Constable Band / Bugler / Drummer",
        "cat_no": "2026",
        "level": "SSLC",
        "duration_minutes": 75,
        "opportunity": "Application window through 7 Oct 2026",
        "apply_by": "2026-10-07",
        "syllabus": [
            {"topic": "History", "marks": 8},
            {"topic": "Geography", "marks": 7},
            {"topic": "Constitution and Polity", "marks": 10},
            {"topic": "Facts About Kerala", "marks": 8},
            {"topic": "Daily Current Affairs", "marks": 10},
            {"topic": "Maths", "marks": 10},
            {"topic": "English", "marks": 10},
            {"topic": "Malayalam", "marks": 10},
            {"topic": "Science", "marks": 7},
            {"topic": "Band Music and Police Special Topics", "marks": 20},
        ],
        "topic_fallbacks": {
            "Band Music and Police Special Topics": ["Arts Culture Literature Sports", "English", "History"],
        },
    },
]

PRIORITY_SLUGS = [item["slug"] for item in PRIORITY_EXAMS]


from typing import Optional

def priority_rank(slug: Optional[str]) -> int:
    if not slug:
        return 999
    for item in PRIORITY_EXAMS:
        if item["slug"] == slug:
            return item["rank"]
    return 999
