# Generated by Django 5.1.6 on 2025-06-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
