# Generated by Django 5.1.6 on 2025-06-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0007_examcategory_exam_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=75, help_text="Exam duration in minutes"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="topic_images/"),
        ),
        migrations.CreateModel(
            name="ExamSyllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_questions", models.PositiveIntegerField(default=10)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_parts",
                        to="questionbank.exam",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionbank.topic",
                    ),
                ),
            ],
            options={
                "unique_together": {("exam", "topic")},
            },
        ),
    ]
