# Generated by Django 5.1.6 on 2025-06-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0005_feeitem_payment"),
        ("questionbank", "0009_userprofile_preferred_exams_alter_examcategory_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="exam",
        ),
        migrations.AddField(
            model_name="question",
            name="exams",
            field=models.ManyToManyField(
                related_name="questions", to="questionbank.exam"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="old_exam",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="questionbank.exam",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="sub_topic",
            field=models.CharField(
                blank=True, help_text="e.g., Indian Freedom Movement", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="institute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions_institute",
                to="institutes.institute",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions_topic",
                to="questionbank.topic",
            ),
        ),
    ]
