# This is a special "data migration" file.
# Its only job is to copy data from the old field to the new one.

from django.db import migrations

def copy_exam_data_to_m2m(apps, schema_editor):
    """
    Finds every Question, looks at its old single 'exam' relationship,
    and adds that same exam to the new 'exams' many-to-many relationship.
    """
    Question = apps.get_model('questionbank', 'Question')
    
    # We loop through every question in the database
    for question in Question.objects.all():
        # Check if there was an exam linked in the old field
        if hasattr(question, 'old_exam') and question.old_exam:
            # Add that same exam to the new many-to-many field.
            # The .add() method is how you create a link in a ManyToManyField.
            question.exams.add(question.old_exam)

class Migration(migrations.Migration):

    dependencies = [
        # This line was automatically generated by Django. Do not change it.
        ('questionbank', '0010_remove_question_exam_question_exams_and_more'),
    ]

    operations = [
        # This tells Django to run our Python function during the migration process.
        migrations.RunPython(copy_exam_data_to_m2m, reverse_code=migrations.RunPython.noop),
    ]