# Generated by Django 5.1.6 on 2025-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0012_remove_question_old_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_content_creator",
            field=models.BooleanField(
                default=False,
                help_text="Designates this user as a trusted community content creator.",
            ),
        ),
    ]
