# Generated by Django 5.1.6 on 2025-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0013_userprofile_is_content_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question")),
                ("option_a", models.CharField(max_length=255, verbose_name="Option A")),
                ("option_b", models.CharField(max_length=255, verbose_name="Option B")),
                (
                    "option_c",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Option C"
                    ),
                ),
                (
                    "option_d",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Option D"
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="Correct Answer",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Explanation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="daily_exams",
                        to="questionbank.questions",
                    ),
                ),
            ],
        ),
    ]
