# Generated by Django 5.1.6 on 2025-07-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0016_modelexam_modelexamattempt"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="modelexamattempt",
            unique_together=set(),
        ),
    ]
