# Generated by Django 5.1.6 on 2025-07-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0017_alter_modelexamattempt_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviousYearPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., LDC Main Exam 2017", max_length=255
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("pdf_file", models.FileField(upload_to="pyq_papers/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyq_papers",
                        to="questionbank.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
    ]
