# Generated by Django 5.1.6 on 2025-07-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0018_previousyearpaper"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_date", models.DateField()),
                ("last_date_to_apply", models.DateField()),
                ("exam_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement",
                        to="questionbank.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["exam_date"],
            },
        ),
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        help_text="Detailed syllabus content. Can include HTML for formatting."
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="syllabuses/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus",
                        to="questionbank.exam",
                    ),
                ),
            ],
        ),
    ]
