# Generated by Django 5.1.6 on 2025-07-12 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0019_examannouncement_syllabus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examannouncement",
            options={"ordering": ["-publication_date"]},
        ),
        migrations.RemoveField(
            model_name="examannouncement",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="examannouncement",
            name="exam_date",
        ),
        migrations.RemoveField(
            model_name="examannouncement",
            name="last_date_to_apply",
        ),
        migrations.RemoveField(
            model_name="examannouncement",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="examannouncement",
            name="notification_date",
        ),
        migrations.AddField(
            model_name="examannouncement",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="exam_programmes/"),
        ),
        migrations.AddField(
            model_name="examannouncement",
            name="publication_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="examannouncement",
            name="title",
            field=models.CharField(
                help_text="e.g., EXAMINATION PROGRAMME FOR THE MONTH OF SEPTEMBER 2025",
                max_length=255,
                null=True,
            ),
        ),
    ]
