# Generated by Django 5.1.6 on 2025-07-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0020_alter_examannouncement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="A short description or bio for the user's public profile.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
    ]
