# Generated by Django 5.0.6 on 2026-06-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0021_userprofile_bio_userprofile_is_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="question",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
