# Generated by Django 5.0.6 on 2026-06-14 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0022_exam_slug_question_slug_topic_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentAffairs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("content", models.TextField(help_text="Full news article details")),
                ("category", models.CharField(default="Kerala", max_length=50)),
                (
                    "publication_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "psc_likelihood",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(blank=True, help_text="AI-generated summary"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Current Affairs",
                "ordering": ["-publication_date", "-created_at"],
            },
        ),
    ]
