# Generated by Django 5.0.6 on 2026-06-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0023_currentaffairs"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_active_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="streak_freeze_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
