# Generated by Django 5.0.6 on 2026-06-15 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0025_studyfeedcard_aiexplanationcache_userfeedview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="previousyearpaper",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Add questions from this paper to enable quiz mode",
                related_name="pyq_papers",
                to="questionbank.question",
            ),
        ),
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("topic", "Topic Practice"),
                            ("difficulty", "Difficulty Drill"),
                            ("mixed", "Mixed Practice"),
                            ("pyq", "Previous Year Questions"),
                            ("weak_area", "Weak Area Drill"),
                        ],
                        max_length=20,
                    ),
                ),
                ("difficulty", models.CharField(blank=True, max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("time_taken_secs", models.PositiveIntegerField(default=0)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questionbank.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_option", models.CharField(blank=True, max_length=1)),
                ("is_correct", models.BooleanField(default=False)),
                ("time_spent_secs", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionbank.question",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="questionbank.practicesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "question")},
            },
        ),
        migrations.AddField(
            model_name="practicesession",
            name="questions",
            field=models.ManyToManyField(
                through="questionbank.SessionAnswer", to="questionbank.question"
            ),
        ),
        migrations.CreateModel(
            name="TopicProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_attempted", models.PositiveIntegerField(default=0)),
                ("total_correct", models.PositiveIntegerField(default=0)),
                ("easy_attempted", models.PositiveIntegerField(default=0)),
                ("easy_correct", models.PositiveIntegerField(default=0)),
                ("medium_attempted", models.PositiveIntegerField(default=0)),
                ("medium_correct", models.PositiveIntegerField(default=0)),
                ("hard_attempted", models.PositiveIntegerField(default=0)),
                ("hard_correct", models.PositiveIntegerField(default=0)),
                ("last_practiced", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="questionbank.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Topic Progress Records",
                "unique_together": {("user", "topic")},
            },
        ),
    ]
