# Generated by Django 5.0.6 on 2026-06-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0026_previousyearpaper_questions_practicesession_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicesession",
            options={},
        ),
        migrations.AlterModelOptions(
            name="topicprogress",
            options={},
        ),
        migrations.AlterField(
            model_name="previousyearpaper",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link questions from this paper to enable quiz mode",
                related_name="pyq_papers",
                to="questionbank.question",
            ),
        ),
        migrations.AlterField(
            model_name="topicprogress",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questionbank.topic"
            ),
        ),
    ]
