# Generated by Django 5.0.6 on 2026-06-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0027_alter_practicesession_options_and_more"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Questions",
        ),
        migrations.AddField(
            model_name="question",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Admin-verified question"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ml", "Malayalam")],
                default="en",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source",
            field=models.CharField(
                blank=True, help_text="e.g., LDC 2023 Paper 1", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.JSONField(
                default=list, help_text="['freedom_struggle','gandhi'] for SEO tagging"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="times_answered",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="times_correct",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year this question appeared in exam", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionbank.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.plan",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_exam_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="dailyexam",
            name="questions",
        ),
        migrations.AddField(
            model_name="dailyexam",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="daily_exams", to="questionbank.question"
            ),
        ),
    ]
