# Generated by Django 5.0.6 on 2026-06-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0029_question_ai_explanation_question_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TVM", "Thiruvananthapuram"),
                    ("KLM", "Kollam"),
                    ("PTA", "Pathanamthitta"),
                    ("ALP", "Alappuzha"),
                    ("KTY", "Kottayam"),
                    ("IDK", "Idukki"),
                    ("EKM", "Ernakulam"),
                    ("TCR", "Thrissur"),
                    ("PKD", "Palakkad"),
                    ("MLP", "Malappuram"),
                    ("KOZ", "Kozhikode"),
                    ("WYD", "Wayanad"),
                    ("KNR", "Kannur"),
                    ("KSD", "Kasaragod"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="questionbank.userprofile"),
        ),
    ]
