# Generated by Django 6.0.6 on 2026-06-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0030_userprofile_district_userprofile_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentaffairs",
            name="mcq",
            field=models.JSONField(
                blank=True, help_text="AI-generated PSC-style MCQ", null=True
            ),
        ),
        migrations.AddField(
            model_name="currentaffairs",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Credible news source URL",
                max_length=500,
                null=True,
            ),
        ),
    ]
