# Generated by Django 6.0.6 on 2026-07-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0031_current_affairs_mcq_sourceurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("ml", "Malayalam")],
                default="en",
                help_text="User's preferred language for practice and quizzes",
                max_length=5,
            ),
        ),
    ]
