# Generated by Django 6.0.6 on 2026-07-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0032_userprofile_preferred_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("wrong_answer", "Wrong Answer Marked as Correct"),
                    ("question_error", "Question Text Has Error"),
                    ("bad_options", "Options Are Wrong / Missing"),
                    ("language_issue", "Language / Malayalam Mix Issue"),
                    ("formatting_issue", "Formatting Problem"),
                    ("other", "Other Issue"),
                ],
                default="other",
                help_text="Category of the problem",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.TextField(help_text="User description of the problem"),
        ),
    ]
