# Generated by Django 6.0.6 on 2026-07-27 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionbank", "0033_add_report_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="User's WhatsApp / Contact phone number",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="primary_exam",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's main primary target exam",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_students",
                to="questionbank.exam",
            ),
        ),
        migrations.CreateModel(
            name="MasterStudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. LGS 2026 Master Coaching Roadmap",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "estimated_days",
                    models.PositiveIntegerField(
                        default=60, help_text="Total target days to complete roadmap"
                    ),
                ),
                (
                    "syllabus_structure",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of subjects, modules, topics with target days",
                    ),
                ),
                (
                    "weekly_milestones",
                    models.JSONField(
                        default=list, help_text="Week-by-week goals and focus areas"
                    ),
                ),
                (
                    "mock_test_schedule",
                    models.JSONField(
                        default=list,
                        help_text="Milestone points for taking full mock exams",
                    ),
                ),
                (
                    "revision_schedule",
                    models.JSONField(
                        default=list, help_text="Spaced repetition revision checkpoints"
                    ),
                ),
                (
                    "pyq_schedule",
                    models.JSONField(
                        default=list, help_text="Schedule for solving past paper sets"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_study_plan",
                        to="questionbank.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserExamProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_topic_ids",
                    models.JSONField(
                        default=list, help_text="List of Topic IDs completed by user"
                    ),
                ),
                (
                    "completed_mock_ids",
                    models.JSONField(
                        default=list, help_text="List of ModelExam IDs completed"
                    ),
                ),
                (
                    "completed_pyq_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of PreviousYearPaper IDs completed",
                    ),
                ),
                ("last_studied", models.DateTimeField(auto_now=True)),
                (
                    "current_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questionbank.topic",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progresses",
                        to="questionbank.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_progresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "exam")},
            },
        ),
    ]
