# Generated by Django 5.1.6 on 2025-06-12 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0001_initial"),
        ("questionbank", "0004_question_institute_topic_institute_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="login_bg_image",
            field=models.ImageField(blank=True, null=True, upload_to="custom_login/"),
        ),
        migrations.AddField(
            model_name="institute",
            name="login_image_1",
            field=models.ImageField(blank=True, null=True, upload_to="custom_login/"),
        ),
        migrations.AddField(
            model_name="institute",
            name="login_image_2",
            field=models.ImageField(blank=True, null=True, upload_to="custom_login/"),
        ),
        migrations.AddField(
            model_name="institute",
            name="login_image_3",
            field=models.ImageField(blank=True, null=True, upload_to="custom_login/"),
        ),
        migrations.AddField(
            model_name="message",
            name="read_by",
            field=models.ManyToManyField(
                blank=True, related_name="read_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="institute_logos/"
            ),
        ),
        migrations.AlterField(
            model_name="institute",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_fees",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "student_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structure",
                        to="questionbank.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("payment_method", models.CharField(default="Offline", max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "fee_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="institutes.feestructure",
                    ),
                ),
            ],
        ),
    ]
