# Generated by Django 5.1.6 on 2025-06-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "institutes",
            "0002_institute_login_bg_image_institute_login_image_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="message_images/"),
        ),
    ]
