# Generated by Django 5.1.6 on 2025-06-15 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0004_institutejoinrequest"),
        ("questionbank", "0005_userprofile_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("tuition", "Tuition"),
                            ("examination", "Examination"),
                            ("library", "Library"),
                            ("sports", "Sports"),
                            ("transport", "Transport"),
                            ("other", "Other"),
                        ],
                        default="tuition",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_items",
                        to="questionbank.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("payment_method", models.CharField(default="Offline", max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="questionbank.userprofile",
                    ),
                ),
            ],
        ),
    ]
