# Generated by Django 5.0.6 on 2026-06-14 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0005_feeitem_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="fee_structure",
        ),
        migrations.AddField(
            model_name="payment",
            name="fee_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="institutes.feeitem",
            ),
        ),
        migrations.DeleteModel(
            name="FeeStructure",
        ),
        migrations.DeleteModel(
            name="PaymentTransaction",
        ),
    ]
