# Generated by Django 5.0.6 on 2026-06-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0006_remove_paymenttransaction_fee_structure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="accent_color",
            field=models.CharField(default="#ff9800", max_length=7),
        ),
        migrations.AddField(
            model_name="institute",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="custom_domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="established_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="institute",
            name="primary_color",
            field=models.CharField(default="#1976d2", max_length=7),
        ),
        migrations.AddField(
            model_name="institute",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="subdomain_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="tagline",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="institute",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
